# Generated by Django 4.1.3 on 2022-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atirgul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('rasm', models.CharField(max_length=255)),
                ('malumot', models.TextField()),
                ('rangi', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kaktus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('rasm', models.CharField(max_length=255)),
                ('malumot', models.TextField()),
                ('rangi', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('rasm', models.CharField(max_length=255)),
                ('malumot', models.TextField()),
                ('rangi', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moychechak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('rasm', models.CharField(max_length=255)),
                ('malumot', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gul',
            new_name='Binafsha',
        ),
    ]
