# Generated by Django 4.1.3 on 2022-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bmw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=50)),
                ('rangi', models.CharField(max_length=20)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Chevrolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=50)),
                ('rangi', models.CharField(max_length=20)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ferrari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=50)),
                ('rangi', models.CharField(max_length=20)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Honda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=50)),
                ('rangi', models.CharField(max_length=20)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Kia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=50)),
                ('rangi', models.CharField(max_length=20)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
    ]
