# Generated by Django 4.1.3 on 2022-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buxoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulteti', models.CharField(max_length=20)),
                ('yonalishlarisoni', models.IntegerField(default=1)),
                ('malumot', models.TextField()),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Navoiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulteti', models.CharField(max_length=20)),
                ('yonalishlarisoni', models.IntegerField(default=1)),
                ('malumot', models.TextField()),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Navoiy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulteti', models.CharField(max_length=20)),
                ('yonalishlarisoni', models.IntegerField(default=1)),
                ('malumot', models.TextField()),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Toshkent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulteti', models.CharField(max_length=20)),
                ('yonalishlarisoni', models.IntegerField(default=1)),
                ('malumot', models.TextField()),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Toshkent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulteti', models.CharField(max_length=20)),
                ('yonalishlarisoni', models.IntegerField(default=1)),
                ('malumot', models.TextField()),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
    ]
