# Generated by Django 4.1.3 on 2022-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Infinix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Redme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('rasmi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
    ]
